"""18 socket-emitting tool definitions (mirrors src/tools/definitions.ts).

Each entry: (name, description, [(arg, type, required)]).
Types: str | float | bool | list | dict.
"""

TOOL_SPECS: list[tuple[str, str, list[tuple[str, str, bool]]]] = [
    ("chalkboard_get_state",
     "Retrieves current board state: strokes, viewport, selection, links. Use to inspect before drawing.",
     [("includeStrokeDetails", "bool", False)]),
    ("chalkboard_draw_chalk",
     "Draws ONE continuous chalk stroke. For multi-part diagrams, call once per component so cursor glides.",
     [("points", "list", True), ("color", "str", False), ("size", "float", False),
      ("intensity", "float", False), ("closed", "bool", False), ("fillColor", "str", False),
      ("pathType", "str", False)]),
    ("chalkboard_write_text",
     "Writes chalk text at (x,y). CRITICAL: Split into 1-3 words per call, textAlign left, preserve color/fontSize across chunks for live cursor glide.",
     [("text", "str", True), ("x", "float", True), ("y", "float", True),
      ("fontSize", "float", False), ("color", "str", False), ("textAlign", "str", False)]),
    ("chalkboard_insert_shape",
     "Inserts one geometric shape at (x,y) or viewport center. One shape per call.",
     [("shape", "str", True), ("x", "float", False), ("y", "float", False)]),
    ("chalkboard_create_note",
     "Creates a rich-text sticky note with HTML.",
     [("content", "str", True), ("x", "float", True), ("y", "float", True),
      ("width", "float", False), ("height", "float", False),
      ("backgroundColor", "str", False), ("textColor", "str", False)]),
    ("chalkboard_highlight_area",
     "Draws focus/correction/praise/answer_box rectangle to guide attention.",
     [("minX", "float", True), ("minY", "float", True), ("maxX", "float", True),
      ("maxY", "float", True), ("label", "str", False), ("type", "str", False)]),
    ("chalkboard_select_and_transform",
     "Mutates existing strokes: delete/nudge/change_color/duplicate. select_only/deselect are local-only (no board change). rotate/change_size/group/ungroup are NOT supported and return errors.",
     [("strokeIds", "list", True), ("action", "str", True), ("rotationDegrees", "float", False),
      ("dx", "float", False), ("dy", "float", False), ("color", "str", False),
      ("size", "float", False)]),
    ("chalkboard_manage_topic_links",
     "Creates/lists/renames/deletes/focuses topic bookmark links.",
     [("action", "str", True), ("tag", "str", False), ("linkId", "str", False),
      ("newTag", "str", False)]),
    ("chalkboard_send_chat",
     "Posts chat message to classroom.",
     [("message", "str", True)]),
    ("chalkboard_speak_narration",
     "Speaks text aloud in the LiveKit voice call via Edge TTS — ONLY works after the owner adds the agent to voice. Returns delivered:true when actually spoken, delivered:false otherwise (then use chalkboard_send_chat). Only call if voice was explicitly requested.",
     [("text", "str", True), ("rate", "float", False), ("pitch", "float", False)]),
    ("chalkboard_clear_or_undo",
     "Undo last stroke or clear the whole board. Redo is NOT supported — returns an error.",
     [("action", "str", True)]),
    ("chalkboard_send_reaction",
     "Sends emoji reaction (visible to all).",
     [("emoji", "str", True)]),
    ("chalkboard_toggle_hand",
     "Raises or lowers hand.",
     [("raised", "bool", True)]),
    ("chalkboard_kick_member",
     "Kicks participant by socketId (instructor).",
     [("targetSocketId", "str", True), ("reason", "str", False)]),
    ("chalkboard_update_member_role",
     "Updates member role instructor<->viewer (owner only).",
     [("targetUserId", "str", True), ("role", "str", True)]),
    ("chalkboard_close_room",
     "Closes room (owner only).",
     [("reason", "str", False)]),
    ("chalkboard_manage_voice",
     "Invite/remove voice (owner).",
     [("action", "str", True), ("targetUserId", "str", False)]),
    ("chalkboard_clipboard",
     "Duplicates the most recent stroke. copy/cut/paste are local UI ops with no board effect and return errors — only duplicate mutates the board.",
     [("action", "str", True)]),
]

EXPECTED_TOOL_NAMES: list[str] = [name for name, _, _ in TOOL_SPECS]
